app/cf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("equipment.urls", namespace='equip')),
    path("admin/", admin.site.urls),
]

app/equipment/urls.py
from django.urls import path

from .views import (
    ComputerCreateView,
    ComputerListView,
    PrinterCreateView,
    PrinterListView,
)

app_name = "equip"

urlpatterns = [
    path("printers/", PrinterListView.as_view(), name="printer-list"),
    path("printer-create/", PrinterCreateView.as_view(), name="printer-create"),
    path("computers/", ComputerListView.as_view(), name="computer-list"),
    path("computer-create/", ComputerCreateView.as_view(), name="computer-create"),
]

app/equipment/models.py
from django.db import models


class Group(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name.upper()


class Manufacturer(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name.upper()


class Equipment(models.Model):
    GRN = "Ground"
    FIRST = "First"
    SECOND = "Second"
    THIRD = "Third"
    
    FLOOR_LIST = (
        (GRN, "Ground"),
        (FIRST, "1st"),
        (SECOND, "2nd"),
        (THIRD, "3rd"),
    )
    group = models.ForeignKey(
        Group, on_delete=models.CASCADE, related_name="equipment_list"
    )
    manufacturer = models.ForeignKey(
        Manufacturer,
        on_delete=models.CASCADE,
        related_name="manufacturer_list",
        null=True,
    )
    name = models.CharField(max_length=100)
    serial_number = models.CharField(max_length=100, unique=True)
    user_section = models.CharField(max_length=100, null=True)
    floor = models.CharField(max_length=100, choices=FLOOR_LIST)
    office = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "equipment"

    def __str__(self):
        return self.name


class Ink(models.Model):
    printer = models.ForeignKey(
        Equipment,
        on_delete=models.CASCADE,
        related_name="ink_list",
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=100, unique=True)
    count = models.PositiveIntegerField(default=1)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "ink"

    def __str__(self):
        return self.name

app/stationery/models.py
from django.db import models

# Create your models here.

app/toiletry/models.py
from django.db import models

# Create your models here.

app/equipment/forms.py
from django import forms

from .models import Equipment


class EquipmentCreateForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = "__all__"

app/equipment/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from .forms import EquipmentCreateForm
from .models import Equipment, Group


class PrinterCreateView(CreateView):
    model = Equipment
    form_class = EquipmentCreateForm
    success_url = reverse_lazy("equip:printer-list")


class PrinterListView(ListView):
    model = Equipment
    printer = Group.objects.get(name__icontains="printer")
    extra_context = {
        "printer_create_form": EquipmentCreateForm(initial={"group": printer})
    }
    template_name = 'equipment/printer_list.html'
    
    def get_queryset(self):
        queryset = Equipment.objects.filter(group__name__icontains='printer')
        return queryset

class ComputerCreateView(CreateView):
    model = Equipment
    form_class = EquipmentCreateForm
    success_url = reverse_lazy("equip:computer-list")


class ComputerListView(ListView):
    model = Equipment
    computer = Group.objects.get(name__icontains="computer")
    extra_context = {
        "computer_create_form": EquipmentCreateForm(initial={"group": computer})
    }
    template_name = 'equipment/computer_list.html'
    
    def get_queryset(self):
        queryset = Equipment.objects.filter(group__name__icontains='computer')
        return queryset
    

app/stationery/views.py
from django.shortcuts import render

# Create your views here.

app/toiletry/views.py
from django.shortcuts import render

# Create your views here.

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">
    <title>

        {% block head_title %}

        {% endblock head_title %}
        Accountant General's Department
    </title>
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
        crossorigin="anonymous">

    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">
    
        <style>
            html, body {
                font-family: 'Montserrat', sans-serif;
            }
        </style>
</head>

<body>

    {% include 'navbar.html' %}

    {% block content %}

    {% endblock content %}

    <script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/equipment/computer_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
Computers -
{% endblock head_title %}

{% block content %}
<div class="border shadow rounded-5 container p-5 col-lg-6 mx-auto">
    <h3 class="text-center">Add Form</h3>
    <hr>
    <form action="{% url 'equip:computer-create' %}"
        method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-6 mx-auto">
                {{ computer_create_form.group|as_crispy_field }}
            </div>
            <div class="col-lg-6">
                {{ computer_create_form.manufacturer|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                {{ computer_create_form.name|as_crispy_field }}
            </div>
            <div class="col-lg-6">
                {{ computer_create_form.serial_number|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                {{ computer_create_form.floor|as_crispy_field }}
            </div>
            <div class="col-lg-4">
                {{ computer_create_form.user_section|as_crispy_field }}
            </div>
            <div class="col-lg-4">
                {{ computer_create_form.office|as_crispy_field }}
            </div>
        </div>
        <br>
        <div class="text-end">
            <button class="btn btn-dark"
                type="submit">Add</i></button>
        </div>
    </form>
</div>
<br>
<hr>
<div class="my-5 table responsive container">
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">User/Section</th>
                <th scope="col">Serial number</th>
                <th scope="col">Floor/Office</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{object.manufacturer}} {{object.name}}</td>
                <td>{{object.user|default:"-"}}/{{object.section|default:"-"}}
                </td>
                <td>{{object.serial_number|upper}}</td>
                <td>{{object.floor|upper|default:"-"}}/{{object.office|upper|default:"-"}}
                </td>
                <td><a class="text-decoration-none text-info"
                        href="{{object.get_absolute_url}}"><i
                            class="bi bi-three-dots-vertical"></i></a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
{% endblock content %}

app/templates/equipment/equipment_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block head_title %}

{% endblock head_title %}


{% block content %}
<form action=""
    method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">+</button>
</form>
<hr>
{% for object in equipment_list %}
{{object}}
{% endfor %}

{% endblock content %}

app/templates/equipment/equipment_list copy.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
Printers -
{% endblock head_title %}

{% block content %}
<div class="border shadow rounded-5 container p-5 col-lg-4 mx-auto">
    <h3 class="text-center">Add Printer</h3>
    <hr>
    <form action="{% url 'equip:printer-create' %}"
        method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-6 mx-auto">
                {{ printer_create_form.group|as_crispy_field }}
            </div>
            <div class="col-lg-6">
                {{ printer_create_form.manufacturer|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                {{ printer_create_form.name|as_crispy_field }}
            </div>
            <div class="col-lg-6">
                {{ printer_create_form.serial_number|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                {{ printer_create_form.user|as_crispy_field }}
            </div>
            <div class="col-lg-6">
                {{ printer_create_form.section|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                {{ printer_create_form.floor|as_crispy_field }}
            </div>
            <div class="col-lg-6">
                {{ printer_create_form.office|as_crispy_field }}
            </div>
        </div>
        <br>
        <div class="text-end">
            <button class="btn btn-dark"
                type="submit">Add printer</i></button>
        </div>
    </form>
</div>
<br>
<hr>
<div class="my-5 table responsive container">
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Printer name</th>
                <th scope="col">Ink Name</th>
                <th scope="col">User/Section</th>
                <th scope="col">Serial number</th>
                <th scope="col">Floor/Office</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{object.manufacturer}} {{object.name}}</td>
                <td>
                    {% for ink in object.ink_list.all %}
                    {{ink}},
                    {% endfor %}
                </td>
                <td>{{object.user|default:"-"}}/{{object.section|default:"-"}}
                </td>
                <td>{{object.serial_number|upper}}</td>
                <td>{{object.floor|upper|default:"-"}}/{{object.office|upper|default:"-"}}
                </td>
                <td><a class="text-decoration-none text-info"
                        href="{{object.get_absolute_url}}"><i
                            class="bi bi-three-dots-vertical"></i></a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
{% endblock content %}

app/templates/equipment/printer_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
Printers -
{% endblock head_title %}

{% block content %}
<div class="border shadow rounded-5 container p-5 col-lg-6 mx-auto">
    <h3 class="text-center">Add Form</h3>
    <hr>
    <form action="{% url 'equip:printer-create' %}"
        method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-6 mx-auto">
                {{ printer_create_form.group|as_crispy_field }}
            </div>
            <div class="col-lg-6">
                {{ printer_create_form.manufacturer|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                {{ printer_create_form.name|as_crispy_field }}
            </div>
            <div class="col-lg-6">
                {{ printer_create_form.serial_number|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                {{ printer_create_form.floor|as_crispy_field }}
            </div>
            <div class="col-lg-4">
                {{ printer_create_form.user_section|as_crispy_field }}
            </div>
            <div class="col-lg-4">
                {{ printer_create_form.office|as_crispy_field }}
            </div>
        </div>
        <br>
        <div class="text-end">
            <button class="btn btn-dark"
                type="submit">Add</i></button>
        </div>
    </form>
</div>
<br>
<hr>
<div class="my-5 table responsive container">
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Printer name</th>
                <th scope="col">Ink Name</th>
                <th scope="col">User/Section</th>
                <th scope="col">Serial number</th>
                <th scope="col">Floor/Office</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{object.manufacturer}} {{object.name}}</td>
                <td>
                    {% for ink in object.ink_list.all %}
                    {{ink}},
                    {% endfor %}
                </td>
                <td>{{object.user|default:"-"}}/{{object.section|default:"-"}}
                </td>
                <td>{{object.serial_number|upper}}</td>
                <td>{{object.floor|upper|default:"-"}}/{{object.office|upper|default:"-"}}
                </td>
                <td><a class="text-decoration-none text-info"
                        href="{{object.get_absolute_url}}"><i
                            class="bi bi-three-dots-vertical"></i></a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
{% endblock content %}

app/templates/navbar.html
<div class="d-flex flex-wrap py-3 shadow mb-5 bg-light px-5">
    <a class="text-dark"
        href="{% url 'equip:printer-list' %}">Printers</a>
    <a class="text-dark mx-3"
        href="{% url 'equip:computer-list' %}">Computers</a>
</div>